### ISSUE TITLE
No "RULES" section in fsc27

### ISSUE THREAD

**Issue by ritafonso** [speciationgenomics/scripts#11]
Hi Joana,

I was using the script calculateAIC.sh and came across an issue. Since I'm using fsc27, the section "RULES" in the .est file is not necessary anymore and I didn't include it. When I ran the AIC script, it only calculates deltaL and fails to calculate AIC. The problem is in line 33, where it tries to find "RULES".

To solve it, I added "[RULES]" in my .est file and left it blank and it worked. Just to let you know and anyone that can have the same issue and struge to figgure it out because it doesn't return any error.

Thanks for you work, it helped me a lot!

Rita

**Comment by yangwukaidi** [comment]
Hi ritafonso.
Yes, I've met the question as you too. I succeeded in solving the problem according to your advice.
Thank you very much.
