### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by jennagrimshaw** [speciationgenomics/scripts#13]
Hello, I used two of the scripts by Joana to analyze my fastsimcoal data (calculateAIC and plotModels) and I would love to cite your work in my publication.  Do you have a citation preference for me to use? I greatly appreciated your scripts! Thanks so much, Jenna

**Comment by joanam** [comment]
Hi Jenna
Great that you are using this. I answered by email long time ago but as others might have the same question, please cite Meier et al. 2017 for demographic modeling scripts: https://pubmed.ncbi.nlm.nih.gov/27613570/
