### ISSUE TITLE
Newest version of checkHetsIndvVCF.sh not working

### ISSUE THREAD

**Issue by CIWa** [speciationgenomics/scripts#15]
Hi Joana and Mark,

thanks a lot for making this repository available to everyone; an awesome resource!

I just wanted to report that the current version of checkHetsIndvVCF.sh is not working. Running it with different vcf-files, some of them zipped, some not, results in the following error:
```
Rscript outputting your plots
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
Execution halted
```
The older version (without x-axsis pruning) works.

Best wishes,
Isabel

**Comment by lpittet92** [comment]
Hello,

**Comment by lpittet92** [comment]
Hello,
I am having the same problem and don't have access to the older version ! Could someone help me with this issue ?

All the best,
Loïc
