### ISSUE TITLE
Outgroup gone missing after 

### ISSUE THREAD

**Issue by smallfishcui** [speciationgenomics/scripts#2]
Hi,

I had made successful calculation with my RAD data when it was aligned to a reference genome using ./convertVCFtoEigenstrat.sh, but when I try denovo vcf, I get error message like this:
Parameters as interpreted:
        --vcf populations.snps.vcf
        --mac 1
        --out populations.snps
        --plink

After filtering, kept 89 out of 89 Individuals
Writing PLINK PED and MAP files ...
Done.
After filtering, kept 40785653 out of a possible 40785653 Sites
Run Time = 15937.00 seconds
parameter file: par.PED.EIGENSTRAT.populations.snps
genotypename: populations.snps.ped
snpname: populations.snps.map
indivname: populations.snps.ped
outputformat: EIGENSTRAT
genotypeoutname: populations.snps.eigenstratgeno
snpoutname: populations.snps.snp
indivoutname: populations.snps.ind
familynames: NO
## convertf version: 5000
*** warning.  genetic distances are in cM not Morgans
1       32061:441       100.001 441

snp order check fail; snp list not ordered: populations.snps.map (processing continues)    1     0     2
zzz 0 38841
snp order check fail; snp list not ordered: populations.snps.map (processing continues)    1     0     2
zzz 1 314788
snp order check fail; snp list not ordered: populations.snps.map (processing continues)    1     0     2
zzz 2 343244
snp order check fail; snp list not ordered: populations.snps.map (processing continues)    1     0     2
zzz 3 365965
snp order check fail; snp list not ordered: populations.snps.map (processing continues)    1     0     2
zzz 4 513517
snp order check fail; snp list not ordered: populations.snps.map (processing continues)    1     0     2
zzz 5 575462
snp order check fail; snp list not ordered: populations.snps.map (processing continues)    1     0     2
zzz 6 583003
snp order check fail; snp list not ordered: populations.snps.map (processing continues)    1     0     2
zzz 7 677528
snp order check fail; snp list not ordered: populations.snps.map (processing continues)    1     0     2

And in the end I get the eigenstrat file without the outgroup sample. When I reduce the SNPs number and keep only the alleles appear in more than 90% of the samples, the outgroup was kept.
Do you know what is the problem?

thanks,
Cui

**Comment by markravinet** [comment]
The error messages are probably to do with how your scaffolds/loci/chromosomes are ordered in the vcf. This is an error from convertf - so you will probably need to edit the plink files before running that on them. Try doing something like setting all scaffolds to 1 or something.

Most likely, by hard filtering your data on MAF > 90% (if I understood correctly) then you have removed markers out of order and so the program retains the outgroup positions.
