### ISSUE TITLE
./plotModel.r -p early_geneflow -l EC,GOLAN

### ISSUE THREAD

**Issue by jingydz** [speciationgenomics/scripts#3]
Hi, when I try the plotModel.r, I got the error message like this:
[root@GenEngine bestrun]# ./plotModel.r -p early_geneflow -l EC,GOLAN
Error in (grep("Population effective sizes", tpl) + 1):(grep("//Haploid",  : 
  argument of length 0
Calls: plotModelBestParams
Execution halted

Do you know how to deal with it?

**Comment by joanam** [comment]
It seems that plotModel.r does not find the texts "Population effective sizes" or "Haploid" in your tpl file. This R script was written for the course and is not very flexible. If you deleted or modified the comments in the tpl file containing these words, plotModel.r will struggle.

**Comment by jingydz** [comment]
![image](https://user-images.githubusercontent.com/45711930/65389408-7fbe9d00-dd88-11e9-8d4a-3e242ebccf9e.png)
Hi,
I am a rookie, this picture is my tpl file. So what should I use to replace the "Haploid" in your plotmodel.r？
The line is https://github.com/speciationgenomics/scripts/blob/master/plotModel.r#L48
and https://github.com/speciationgenomics/scripts/blob/master/plotModel.r#L49

**Comment by joanam** [comment]
In your tpl file replace "//Samples sizes and samples age" by "//Haploid samples sizes and samples age". I have uploaded all the demographic model .est, .tpl and .obs files to [data](https://github.com/speciationgenomics/data).

**Comment by jingydz** [comment]
Ok, I found it! Thank you!
