### ISSUE TITLE
plotADMIXTURE.r  not working for K=2

### ISSUE THREAD

**Issue by Marvin02860** [speciationgenomics/scripts#6]
Hello,
I find the plotADMIXTURE.r script very useful, but I cannot make it work for K=2 (only for K=4).
When I try, I get the following message: 

Error in tbl[[x]] : subscript out of bounds
Calls: lapply -> FUN -> barplot -> t -> as.matrix
Execution halted

Could it be a mistake in the script itself?
Thank you for your help.
Kind regards.

**Comment by joanam** [comment]
Dear Marvin,
Thanks for pointing this out. I have now increased the flexibility of the script to allow for a maximum K of 2.
Best,
Joana

**Comment by Marvin02860** [comment]
Dear Joana, 
Thank you very much for this improvement, this works very well.

However, I see that the option "-m" is available to specify the minimum number of K, and I would also like to use it.
If I try to use this option for min K = 4, in order to keep only the graph for K=4, the same problem happens again:
Error in tbl[[x]] : subscript out of bounds
Calls: lapply -> FUN -> barplot -> t -> as.matrix
Execution halted

Thank you again for your help.
Marvin

**Comment by joanam** [comment]
Dear Marvin,
Thanks for the feedback. 
Please try it now. I am actually taking some days off and I cannot test the code. Please let me know if it works. 
Best,
Joana

**Comment by Marvin02860** [comment]
Dear Joana,
Thank you, yes it is better now!
Only the line: 
' bp<-barplot(t(as.matrix(tbl[[1]][order(labels$n),])), col=rainbow(n=minK),xaxt="n", border=NA,ylab="K="minK, '
is problematic, but I replaced ' ylab="K" minK ' by ' ylab="K=4" ' to suit my own test, so I am good with that :)

Thank you very much for your help!
All the best,
Marvin

**Comment by joanam** [comment]
Many thanks. I have fixed that issue now as well! Thanks for reporting back and I am glad that it works now.
Best,
Joana
