### ISSUE TITLE
fsc-selectbestrun

### ISSUE THREAD

**Issue by smallfishcui** [speciationgenomics/scripts#9]
Hi,

Thanks for the course material. Although I m not able to attend the course on site, I have learnt lots of skills here!
The procedure with fastsimcoal has been running fine before, but I just lately encountered this error when using ./fsc-selectbestrun.sh 
"no .bestlhoods file found in run1
./fsc-selectbestrun.sh: line 37: [: -gt: unary operator expected
no .bestlhoods file found in run10
./fsc-selectbestrun.sh: line 37: [: -gt: unary operator expected
no .bestlhoods file found in run100
./fsc-selectbestrun.sh: line 37: [: -gt: unary operator expected
no .bestlhoods file found in run11
"
It seems to have an easy fix, however I m not an advanced linux user, can you help with that?
Thanks a lot!
Cui

**Comment by joanam** [comment]
Hi Cui,
I am glad you find the course information useful.
Maybe you have figured it out by now. But this script requires a specific folder structure with different runs in folders called run1, run2 etc. In each such folder, it expects to find a subfolder with the model name (generated by fsc) which contains a bestlhoods file. If you have a different folder structure, the selectbestrun.sh script may fail.
I hope that helps.
Best,
Joana
